services:
  mongo:
    image: mongo
    container_name: thread-mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: thread-app
    environment:
      - NODE_ENV=production
    ports:
      - '5000:5000'
    depends_on:
      - mongo

volumes:
  mongo-data: