services:
  mongo:
    image: mongo
    container_name: thread-mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: thread-server
    volumes:
      - ./server:/app/server
      - /app/server/node_modules
    environment:
      - NODE_ENV=development
    ports:
      - '5000:5000'
    command: npm run dev
    depends_on:
      - mongo

  client:
    image: node:20.19.0
    container_name: thread-client
    working_dir: /app/client
    volumes:
      - ./client:/app/client
      - /app/client/node_modules
    ports:
      - '5137:5137'
    command: sh -c "npm install && npm run dev"
    depends_on:
      - server

volumes:
  mongo-data: