services:
  mongo:
    image: mongo
    container_name: blog-mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: blog-app
    environment:
      - NODE_ENV=production
      - MONGO_URL=mongodb://mongo:27017/blog
    ports:
      - '5000:5000'
    depends_on:
      - mongo

volumes:
  mongo-data: